//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gsb_bureau
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gsbEntities : DbContext
    {
        public gsbEntities()
            : base("name=gsbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dosage> dosage { get; set; }
        public virtual DbSet<famille> famille { get; set; }
        public virtual DbSet<medicament> medicament { get; set; }
        public virtual DbSet<praticien> praticien { get; set; }
        public virtual DbSet<prescrire> prescrire { get; set; }
        public virtual DbSet<type_individu> type_individu { get; set; }
    }
}
